pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t c2odev/example-webserver .

push:
  image: docker
  environment:
    - PASS=${HUB_PASS}
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
   commands:
   - docker login -u c2odev -p $PASS
   - docker push c2odev/example-webserver

deploy:
  image: docker
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  commands:
    - docker pull c2odev/example-webserver
    - docker stack deploy -c ./docker-compose.yml example-webserver

